before:
  hooks:
    - make generate
    - export LD_FLAGS="-X github.com/onflow/flow-cli/build.commit={{ .Env.COMMIT }} -X github.com/onflow/flow-cli/build.semver={{ .Env.VERSION }} -X github.com/onflow/flow-cli/internal/command.mixpanelToken={{ .Env.MIXPANEL_PROJECT_TOKEN }} -X github.com/onflow/flow-cli/internal/accounts.accountToken={{ .Env.LILICO_TOKEN }}"

builds:
  - id: darwin-amd64
    main: ./cmd/flow
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - {{ .Env.LD_FLAGS }}

  - id: darwin-arm64
    main: ./cmd/flow
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - {{ .Env.LD_FLAGS }}

  - id: linux-amd64
    main: ./cmd/flow
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=oa64-x86_64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - {{ .Env.LD_FLAGS }}

  - id: linux-arm64
    main: ./cmd/flow
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=oa64-aarch64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - {{ .Env.LD_FLAGS }}

archives:
  - id: golang-cross
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
      - linux-arm64
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: false
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}.md5"
  algorithm: md5
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  skip: true
release:
  github:
    owner: onflow
    name: flow-cli
  prerelease: auto
  draft: false