before:
  hooks:
    - make generate

builds:
  - id: flow-cli
    main: ./cmd/flow
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang CXX=o64-clang++{{- end }}
          {{- if eq .Arch "arm64"}}CC=oa64-clang CXX=oa64-clang++{{- end }}
        {{- end }}
        {{ if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-linux-gnu-gcc CXX=x86_64-linux-gnu-g++{{- end }}
          {{- if eq .Arch "arm64" }}CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++{{- end }}
          {{- if eq .Arch "arm64" }}CC=aarch64-w64-mingw32-gcc CXX=aarch64-w64-mingw32-g++{{- end }}
        {{- end }}
    flags:
      - -mod=readonly
    ldflags:
      - -X github.com/onflow/flow-cli/build.commit={{ .Env.COMMIT }} -X github.com/onflow/flow-cli/build.semver={{ .Env.VERSION }} -X github.com/onflow/flow-cli/internal/command.mixpanelToken={{ .Env.MIXPANEL_PROJECT_TOKEN }} -X github.com/onflow/flow-cli/internal/accounts.accountToken={{ .Env.LILICO_TOKEN }}

archives:
  - id: golang-cross
    builds:
      - flow-cli
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: false
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  skip: true
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: onflow
    name: flow-cli
  prerelease: auto
  draft: false