name: Delete GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo_owner:
        description: 'Owner of the repo (user or org)'
        required: true
      repo_name:
        description: 'Name of the repo to delete'
        required: true

jobs:
  delete_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Delete GitHub repository
        env:
          GH_TOKEN: ${{ secrets.COMMITTER_TOKEN }}  # Inject your custom token here
          REPO_OWNER: ${{ github.event.inputs.repo_owner }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
        run: |
          echo "🔴 Attempting to delete repository: $REPO_OWNER/$REPO_NAME"

          response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME")

          if [ "$response" == "204" ]; then
            echo "✅ Repository $REPO_OWNER/$REPO_NAME successfully deleted."
          else
            echo "❌ Failed to delete repo. HTTP status: $response"
            exit 1
          fi