name: 🚀 Deploy

on:
  push:
    branches:
      - gpavlov/detect-renamed-docs
      - master
    paths:
      - '**.md'
      - '**.mdx'
  pull_request:
    branches: [ master ]
    paths:
      - '**.md'
      - '**.mdx'

jobs:
  detect:
    name: Detect renamed docs (.md files)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 2
      - run: echo "$(git -P show ${{ github.sha }})"
      - name: Fails if any doc files (.md) were renamed or deleted
        # grep exit code is 0 if a match found, for github actions 0 is success
        run: |
          ! git -P show ${{ github.sha }} --diff-filter=DR | grep 'deleted\|rename'

      
     

  
